language: node_js
node_js:
    - "4.2.1"
sudo: false
before_install:
    - export BASE_BRANCH=master
    - if ( git ls-remote --exit-code https://github.com/smart-facility/cognicity-reports.git $TRAVIS_BRANCH ); then export BASE_BRANCH=$TRAVIS_BRANCH; fi
    - echo "BASE_BRANCH=$BASE_BRANCH"
    - git clone --depth=50 --branch=$BASE_BRANCH https://github.com/smart-facility/cognicity-reports.git smart-facility/cognicity-reports
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/smart-facility/cognicity-reports-powertrack.git smart-facility/cognicity-reports/gnip-powertrack
    - cd smart-facility/cognicity-reports
    - npm install
    - cd gnip-powertrack
